language: ruby
cache:
  bundler: true
services:
- postgresql
before_install:
- gem update --no-document --remote bundler
before_script:
- rm -rf public/packs*/
- bundle exec rake db:test:prepare
script:
- bundle exec rake test
- bundle exec rubocop
