language: ruby
cache:
  bundler: true
services:
- postgresql
before_install:
- gem update --no-document --remote bundler
before_script:
- rm -rf public/packs*/
- RAILS_ENV=test bundle exec rake db:test:prepare
script:
- RAILS_ENV=test bundle exec rake test
- RAILS_ENV=test bundle exec rubocop
